// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"godemo/internal/handler"
	"godemo/internal/repository"
	"godemo/internal/service"
	"godemo/internal/wire/provider"
)

// Injectors from wire.go:

// InitializeAPI 完整依赖注入
func InitializeAPI() (*handler.UserHandler, error) {
	mainDBName := _wireMainDBNameValue
	mainDB := provider.ProvideMainDB(mainDBName)
	userRepository := repository.NewUserRepository(mainDB)
	mainCacheName := _wireMainCacheNameValue
	mainCache := provider.ProvideMainCache(mainCacheName)
	userService := service.NewUserService(userRepository, mainCache)
	userHandler := handler.NewUserHandler(userService)
	return userHandler, nil
}

var (
	_wireMainDBNameValue    = provider.MainDBNameValue
	_wireMainCacheNameValue = provider.MainCacheNameValue
)
